# Como criar e manipular bancos de dados SQL com Python

Acessar página do artigo no [Copiar o link e colar no navegador](obsidian://open?vault=Database&file=%F0%9F%97%82%EF%B8%8F%20Python%2FComo%20criar%20e%20manipular%20bancos%20de%20dados%20SQL%20com%20Python)

### 1. Importar as bibliotecas

In [1]:
import mysql.connector
from mysql.connector import Error
import pandas as pd

Importamos a função **Error** para ter acesso fácil a ela nas funções do tutorial

### 2. Conectando ao MySQL server

A essa altura é preciso ter o Mysql Community Server instalado e configurado no sistema. Agora, iremos escrever um código em Python que nos permita estabelecer uma conexão com esse servidor. 

In [5]:
def create_server_connection(host_name, user_name, user_password): # Na primeira linha, damos um nome a função (create_server_connection) e aos seus argumentos (host_name, user_name e user_password).
    connection = None # Na segunda linha, encerramos quaisquer conexões existentes para que o servidor não fique confuso com várias conexões abertas
    try: # Em seguida, usamos o bloco try-except do Python, para lidar com possíveis erros.
        connection = mysql.connector.connect( # A primeira parte tenta criar uma conexão com o servidor usando o método mysql.connector.connect e os detalhes especificados pelo usuários nos argumentos da função.
            host=host_name,
            user=user_name,
            passwd=user_password
        )
        print("MySQL Database connection successful") # Se funcionar, a função imprime uma pequena mensagem de sucesso 
    except Error as err: # Já o bloco except imprime o erro que o MySQL retorna se, houver um erro.
        print(f"Error: '{err}'") # Por fim, se a conexão for bem sucedida, a função retornará um objeto de conexão.

    return connection # Na prática, atribuímos o resultado dessa função a uma variável, que então se torna o nosso objeto de conexão. Podemos, depois disso, aplicar outros métodos, como o cursor, ao objeto e criar outros objetos úteis. 

pw = "root" # IMPORTANT! Put your MySQL Terminal password here.
db = "school" # This is the name of the database we will create in the next step - call it whatever you like.

connection = create_server_connection("172.17.0.2", "root", pw)

MySQL Database connection successful


Essa é uma função para se conectar ao MySQL Server. 

É uma boa prática a criação de uma função para tornar reutilizável um código como esse, permitindo que ele seja utilizado repetidas vezes com o mínimo de esforço. Uma vez criado, você poderá reutilizá-lo em todos os seus projetos futuros e o seu “eu do futuro” será grato!

Vamos revisar o código, linha por linha, para entendermos o que está acontecendo aqui:

Na primeira linha, damos um nome à função (create\_server\_connection) e aos seus argumentos (host\_name, user\_name e user\_password).

Na linha seguinte, encerramos quaisquer conexões existentes para que o servidor não fique confuso com várias conexões abertas.

Em seguida, usamos um  [bloco try-except](https://www.w3schools.com/python/python_try_except.asp) (texto em inglês) do Python para lidar com possíveis erros. A primeira parte tenta criar uma conexão com o servidor usando o [método mysql.connector.connect()](https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysql-connector-connect.html) (texto em inglês) e os detalhes especificados pelo usuário nos argumentos da função. Se isso funcionar, a função imprime uma pequena mensagem de sucesso.

O código referente ao bloco except imprime o erro que o MySQL Server retorna se, infelizmente, houver um erro.

Por fim, se a conexão for bem-sucedida, a função retornará um [objeto de conexão](https://dev.mysql.com/doc/connector-python/en/connector-python-example-connecting.html) (texto em inglês).

Na prática, atribuímos o resultado dessa função a uma variável, que então se torna o nosso objeto de conexão. Podemos, depois disso, aplicar outros métodos, como o [cursor](https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlcursor.html) (texto em inglês), a ele e criar outros objetos úteis.

### 3. Criando um banco de dados

Depois de estabelecer conexão, o próximo passo é criar um banco de dados no servidor. 

Faremos uma única vez, mas, já deixaremos uma função pronta e reutilizável de modo que tenhamos um código para utilizar em projetos futuros. 

In [6]:
def create_database(connection, query): # Essa função recebe dois argumentos: connection (nosso objeto de conexão) e query (um código SQL que escreveremos na próxima etapa, para executar a query no servidor através da conexão)
    cursor = connection.cursor() # Esse é o método cursor do nosso objeto de conexão, para criar um objeto do tipo cursor (O MySQL usa o paradigma de programação orientada a objetos, portanto, há muitos objetos herdando propriedades do objeto pai)
    try:
        cursor.execute(query) # Este objeto cursor possui métodos como execute, executemany  (que usaremos nesse tutorial)
        print("Database created successfully")
    except Error as err:
        print(f"Error: '{err}'")

create_database_query = "CREATE DATABASE school" # Query para criar um novo banco de dados chamado "school"
create_database(connection, create_database_query) # Comando para executar a função

Error: '1007 (HY000): Can't create database 'school'; database exists'


Essa função recebe dois argumentos, connection (nosso objeto de conexão) e query (um código SQL que escreveremos na próxima etapa). Ela executa a consulta no servidor através da conexão.

Usamos o método [cursor](https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlcursor.html) do nosso objeto de conexão para criar um objeto do tipo cursor (o MySQL Connector usa o [paradigma de programação orientado a objetos](https://www.freecodecamp.org/portuguese/news/como-explicar-conceitos-de-programacao-orientada-a-objetos-para-uma-crianca-de-6-anos/), portanto, há muitos objetos herdando propriedades de objetos pai).

Este objeto cursor possui métodos como [execute](https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlcursor-execute.html), [executemany](https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlcursor-executemany.html) (que usaremos neste tutorial - textos em inglês) assim como vários outros métodos úteis.

Se ajudar, podemos pensar que o objeto cursor dá acesso ao cursor que fica piscando em um terminal do MySQL Server.

![image-148](https://www.freecodecamp.org/portuguese/news/content/images/2022/02/image-148.png)

É disso que estamos falando.

Em seguida, definimos uma consulta para criar o banco de dados e executar a função:

![image-149-1](https://www.freecodecamp.org/portuguese/news/content/images/2022/02/image-149-1.png)

Todos os códigos SQL deste tutorial estão explicados [na minha série de tutoriais Introduction to SQL](https://towardsdatascience.com/tagged/sql-series) (Introdução ao SQL, em inglês), e o código completo está disponível em um Jupyter Notebook neste [repositório do GitHub](https://github.com/thecraigd/Python_SQL). Portanto, não explicarei o que o código SQL faz neste tutorial.

No entanto, esse é talvez o código SQL mais simples possível. Se você pode ler em inglês, provavelmente pode descobrir o que ele faz!

Executar a função create\_database com os argumentos acima resulta na criação de um banco de dados chamado 'school' em nosso servidor.

O banco de dados se chama school pois será implementado um banco de dados para uma escola de idiomas fictícia. O diagrama entidade-relacionamento se encontra no Jupyter do GitHub. 

### 4. Conectado ao banco de dados

Agora que criamos um banco de dados no MySQL Server, podemos modificar nossa função create_server_connection para conectar diretamente a esse banco de dados.

Observe que é possível - comum, na verdade - ter vários bancos de dados em um servidor MySQL, então queremos nos conectar sempre e automaticamente ao banco de dados em que estamos interessados.

Podemos fazer da seguinte maneira:

In [7]:
def create_db_connection(host_name, user_name, user_password, db_name):
    connection = None
    try:
        connection = mysql.connector.connect(
            host=host_name,
            user=user_name,
            passwd=user_password,
            database=db_name # Agora, temos mais um argumento, que é o nome do banco de dados
        )
        print("MySQL Database connection successful")
    except Error as err:
        print(f"Error: '{err}'")

    return connection

Essa é exatamente a mesma função, mas agora temos mais um argumento - o nome do banco de dados - que é passado para o método connect()

💡 Para que serve o **Connect()**? 
 
- Para criar ou obter um objeto de conexão MySQL. Na sua forma mais simples, o método connect() irá abrir uma conexão com um servidor MySql e retornar um objeto MySQlConnection. Quando quaisquer argumentos de pool de conexão são fornecidos, por exemplo pool_name ou pool_size, um pool é criado ou um anteriormente criado é usado para retornar um PooledMySQLConnection.
- Retornar MySQLConnection ou PooledMySQLConnection.

### 5. Criando uma função para executar queries

A última função que criaremos (por enquanto) é extremamente vital - uma função de execução de query. Ela pegará nossas consultas SQL, armazenadas como strings do Python, e as passará para que o método cursor.execute() as execute no servidor.

In [8]:
def execute_query(connection, query):
    cursor = connection.cursor()
    try:
        cursor.execute(query)
        connection.commit() # Método connection.commit para garantir que os comandos detalhados em nossas queries SQL sejam implementados.
        print("Query successful")
    except Error as err:
        print(f"Error: '{err}'")

Essa função é idêntica à nossa função create\_database, exceto por usar o método [connection.commit()](https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlconnection-commit.html) para garantir que os comandos detalhados em nossas consultas SQL sejam implementados.

Essa função será nosso carro-chefe, que usaremos (junto com create\_db\_connection) para criar tabelas, estabelecer relacionamentos entre essas tabelas, preencher as tabelas com dados e atualizar e excluir registros em nosso banco de dados.

Se você for um especialista em SQL, essa função permitirá que você execute todos e quaisquer comandos e consultas complexas que você possa ter, diretamente de um script em Python. Ela pode ser uma ferramenta muito poderosa para gerenciar seus dados.

### 6. Criando tabelas

Agora, estamos prontos para executar comandos SQL no servidor e começar a construir o banco de dados. A primeira coisa que queremos fazer é criar as tabelas necessárias. 

Vamos começar pela tabela Teacher:

In [9]:
# Assign our SQL command to a python variable using triple quotes to create a multi-line string
create_teacher_table = """
CREATE TABLE teacher (
  teacher_id INT PRIMARY KEY,
  first_name VARCHAR(40) NOT NULL,
  last_name VARCHAR(40) NOT NULL,
  language_1 VARCHAR(3) NOT NULL,
  language_2 VARCHAR(3),
  dob DATE,
  tax_id INT UNIQUE,
  phone_no VARCHAR(20)
  );
 """

connection = create_db_connection("172.17.0.2", "root", pw, db) # Connect to the Database
execute_query(connection, create_teacher_table) # Execute our defined query

MySQL Database connection successful
Query successful


Primeiro, atribuímos nosso comando SQL (explicado em detalhes aqui) a uma variável com um nome apropriado, no exemplo, demos o nome de "create_teacher_table". 

Neste caso, usamos a [notação de aspas triplas do Python para definir strings que se estendem por múltiplas linhas](https://developers.google.com/edu/python/strings) (texto em inglês) para armazenar nossa consulta SQL. Então, nós a passamos para a função execute\_query que a executará.

Observe que essa formatação de várias linhas é puramente para facilitar a leitura do código por humanos. Nem SQL nem Python 'se importam' se o comando SQL estiver distribuído dessa maneira. Desde que a sintaxe esteja correta, ambas as linguagens a aceitarão.

Para o bem dos humanos que lerão seu código (mesmo que seja apenas o você do futuro!), é muito útil empregar essa formatação para tornar o código mais legível e compreensível.

O mesmo vale para o uso de expressões do SQL em LETRAS MAIÚSCULAS. Esta é uma convenção amplamente usada e que é fortemente recomendada, mas o software real que executa o código não diferencia maiúsculas de minúsculas e tratará 'CREATE TABLE teacher' e 'create table teacher' como comandos idênticos.

![image-151](https://www.freecodecamp.org/portuguese/news/content/images/2022/02/image-151.png)

A execução deste código retorna nossas mensagens de sucesso. Também podemos verificar isso no client na linha de comando do MySQL Server:

![image-152](https://www.freecodecamp.org/portuguese/news/content/images/2022/02/image-152.png)

Excelente! Agora vamos criar as tabelas restantes.

### 7. Criando as tabelas restantes

In [11]:
create_client_table = """
CREATE TABLE client (
  client_id INT PRIMARY KEY,
  client_name VARCHAR(40) NOT NULL,
  address VARCHAR(60) NOT NULL,
  industry VARCHAR(20)
);
 """

create_participant_table = """
CREATE TABLE participant (
  participant_id INT PRIMARY KEY,
  first_name VARCHAR(40) NOT NULL,
  last_name VARCHAR(40) NOT NULL,
  phone_no VARCHAR(20),
  client INT
);
"""

create_course_table = """
CREATE TABLE course (
  course_id INT PRIMARY KEY,
  course_name VARCHAR(40) NOT NULL,
  language VARCHAR(3) NOT NULL,
  level VARCHAR(2),
  course_length_weeks INT,
  start_date DATE,
  in_school BOOLEAN,
  teacher INT,
  client INT
);
"""


connection = create_db_connection("172.17.0.2", "root", pw, db)
execute_query(connection, create_client_table)
execute_query(connection, create_participant_table)
execute_query(connection, create_course_table)

MySQL Database connection successful
Query successful
Query successful
Query successful


Esses comandos criarão as quatro tabelas necessárias para nossas quatro entidades.

Agora, vamos definir os relacionamentos entre elas e criar mais uma tabela para lidar com o relacionamento muitos-para-muitos entre as tabelas participant e course (participante e curso, em inglês, respectivamente). Veja mais detalhes [aqui](https://towardsdatascience.com/designing-a-relational-database-and-creating-an-entity-relationship-diagram-89c1c19320b2) (texto em inglês).

### 8. Definindo o relacionamento das chaves estrangeiras 

Agora, alterando as tabelas para criar relacionamentos de chave estrangeira (consulte a série de tutoriais SQL em Towards Data Science para obter informações sobre tudo isso) e criando nossa tabela final, takes_course

In [13]:
alter_participant = """
ALTER TABLE participant
ADD FOREIGN KEY(client)
REFERENCES client(client_id)
ON DELETE SET NULL;
"""

alter_course = """
ALTER TABLE course
ADD FOREIGN KEY(teacher)
REFERENCES teacher(teacher_id)
ON DELETE SET NULL;
"""

alter_course_again = """
ALTER TABLE course
ADD FOREIGN KEY(client)
REFERENCES client(client_id)
ON DELETE SET NULL;
"""

create_takescourse_table = """
CREATE TABLE takes_course (
  participant_id INT,
  course_id INT,
  PRIMARY KEY(participant_id, course_id),
  FOREIGN KEY(participant_id) REFERENCES participant(participant_id) ON DELETE CASCADE, -- it makes no sense to keep this rtelation when a participant or course is no longer in the system, hence why CASCADE this time
  FOREIGN KEY(course_id) REFERENCES course(course_id) ON DELETE CASCADE
);
"""

connection = create_db_connection("172.17.0.2", "root", pw, db)
execute_query(connection, alter_participant)
execute_query(connection, alter_course)
execute_query(connection, alter_course_again)
execute_query(connection, create_takescourse_table)

MySQL Database connection successful
Query successful
Query successful
Query successful
Query successful


Agora, nossas tabelas foram criadas, juntamente com as restrições apropriadas e as relações entre chaves primárias e chaves estrangeiras.


### 9. Preenchendo as tabelas

A próxima etapa é adicionar alguns registros às tabelas. Novamente, usaremos a função execute\_query para enviar nossos comandos SQL existentes ao servidor. Vamos começar mais uma vez com a tabela Teacher.

Aqui, novamente atribuímos uma string de várias linhas com nosso comando SQL a uma variável e, em seguida, chamamos nossas funções create_db_connection e execute_query.

In [14]:
pop_teacher = """
INSERT INTO teacher VALUES
(1,  'James', 'Smith', 'ENG', NULL, '1985-04-20', 12345, '+491774553676'),
(2, 'Stefanie',  'Martin',  'FRA', NULL,  '1970-02-17', 23456, '+491234567890'), 
(3, 'Steve', 'Wang',  'MAN', 'ENG', '1990-11-12', 34567, '+447840921333'),
(4, 'Friederike',  'Müller-Rossi', 'DEU', 'ITA', '1987-07-07',  45678, '+492345678901'),
(5, 'Isobel', 'Ivanova', 'RUS', 'ENG', '1963-05-30',  56789, '+491772635467'),
(6, 'Niamh', 'Murphy', 'ENG', 'IRI', '1995-09-08',  67890, '+491231231232');
"""

connection = create_db_connection("172.17.0.2", "root", pw, db)
execute_query(connection, pop_teacher)

MySQL Database connection successful
Query successful


Agora, vamos checar no terminal do MySQL se funcionou.

In [ ]:
SELECT *
FROM teacher; 

### 10. Populando as tabelas restantes

In [16]:
pop_client = """
INSERT INTO client VALUES
(101, 'Big Business Federation', '123 Falschungstraße, 10999 Berlin', 'NGO'),
(102, 'eCommerce GmbH', '27 Ersatz Allee, 10317 Berlin', 'Retail'),
(103, 'AutoMaker AG',  '20 Künstlichstraße, 10023 Berlin', 'Auto'),
(104, 'Banko Bank',  '12 Betrugstraße, 12345 Berlin', 'Banking'),
(105, 'WeMoveIt GmbH', '138 Arglistweg, 10065 Berlin', 'Logistics');
"""

pop_participant = """
INSERT INTO participant VALUES
(101, 'Marina', 'Berg','491635558182', 101),
(102, 'Andrea', 'Duerr', '49159555740', 101),
(103, 'Philipp', 'Probst',  '49155555692', 102),
(104, 'René',  'Brandt',  '4916355546',  102),
(105, 'Susanne', 'Shuster', '49155555779', 102),
(106, 'Christian', 'Schreiner', '49162555375', 101),
(107, 'Harry', 'Kim', '49177555633', 101),
(108, 'Jan', 'Nowak', '49151555824', 101),
(109, 'Pablo', 'Garcia',  '49162555176', 101),
(110, 'Melanie', 'Dreschler', '49151555527', 103),
(111, 'Dieter', 'Durr',  '49178555311', 103),
(112, 'Max', 'Mustermann', '49152555195', 104),
(113, 'Maxine', 'Mustermann', '49177555355', 104),
(114, 'Heiko', 'Fleischer', '49155555581', 105);
"""

pop_course = """
INSERT INTO course VALUES
(12, 'English for Logistics', 'ENG', 'A1', 10, '2020-02-01', TRUE,  1, 105),
(13, 'Beginner English', 'ENG', 'A2', 40, '2019-11-12',  FALSE, 6, 101),
(14, 'Intermediate English', 'ENG', 'B2', 40, '2019-11-12', FALSE, 6, 101),
(15, 'Advanced English', 'ENG', 'C1', 40, '2019-11-12', FALSE, 6, 101),
(16, 'Mandarin für Autoindustrie', 'MAN', 'B1', 15, '2020-01-15', TRUE, 3, 103),
(17, 'Français intermédiaire', 'FRA', 'B1',  18, '2020-04-03', FALSE, 2, 101),
(18, 'Deutsch für Anfänger', 'DEU', 'A2', 8, '2020-02-14', TRUE, 4, 102),
(19, 'Intermediate English', 'ENG', 'B2', 10, '2020-03-29', FALSE, 1, 104),
(20, 'Fortgeschrittenes Russisch', 'RUS', 'C1',  4, '2020-04-08',  FALSE, 5, 103);
"""

pop_takescourse = """
INSERT INTO takes_course VALUES
(101, 15),
(101, 17),
(102, 17),
(103, 18),
(104, 18),
(105, 18),
(106, 13),
(107, 13),
(108, 13),
(109, 14),
(109, 15),
(110, 16),
(110, 20),
(111, 16),
(114, 12),
(112, 19),
(113, 19);
"""

connection = create_db_connection("172.17.0.2", "root", pw, db)
execute_query(connection, pop_client)
execute_query(connection, pop_participant)
execute_query(connection, pop_course)
execute_query(connection, pop_takescourse)

MySQL Database connection successful
Query successful
Query successful
Query successful
Query successful


Acabamos de criar um banco de dados completo com relações, restrições e registros no MySQL, usando apenas comandos em Python.

Fizemos isso passo a passo para que o processo fosse compreensível. Mas a esta altura você já deve ter percebido que todos esses comandos podem facilmente ser incluídos em um script em Python e executados em um único comando no terminal.

## 11. Lendo os dados
### 11.1 Definindo a função de leitura dos dados

gora, temos um banco de dados funcional com o qual podemos trabalhar. Como analista de dados, é provável que você entre em contato com bancos de dados existentes nas organizações em que trabalha. Será muito útil saber como extrair dados desses bancos de dados para que possam ser alimentados em seu pipeline de dados em Python. É nisso que vamos trabalhar a seguir.

Para isso, precisaremos de mais uma função, desta vez, usando [cursor.fetchall()](https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlcursor-fetchall.html) em vez de [cursor.commit()](https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlconnection-commit.html) (textos das duas funções em inglês). Com esta função, leremos dados do banco de dados sem fazer nenhuma alteração.

In [17]:
def read_query(connection, query):
    cursor = connection.cursor()
    result = None
    try:
        cursor.execute(query)
        result = cursor.fetchall() # Em vez de usar o cursor.commit(), vamos usar o cursor.fetchall(). Com essa função, leremos os dados do banco sem fazer nenhuma alteração. 
        return result
    except Error as err:
        print(f"Error: '{err}'")

Novamente, vamos implementar isso de uma maneira muito semelhante ao execute_query. Vamos testar com uma consulta simples para ver como funciona.

In [18]:
q1 = """
SELECT *
FROM teacher;
"""

connection = create_db_connection("172.17.0.2", "root", pw, db)
results = read_query(connection, q1)

for result in results:
  print(result)

MySQL Database connection successful
(1, 'James', 'Smith', 'ENG', None, datetime.date(1985, 4, 20), 12345, '+491774553676')
(2, 'Stefanie', 'Martin', 'FRA', None, datetime.date(1970, 2, 17), 23456, '+491234567890')
(3, 'Steve', 'Wang', 'MAN', 'ENG', datetime.date(1990, 11, 12), 34567, '+447840921333')
(4, 'Friederike', 'Müller-Rossi', 'DEU', 'ITA', datetime.date(1987, 7, 7), 45678, '+492345678901')
(5, 'Isobel', 'Ivanova', 'RUS', 'ENG', datetime.date(1963, 5, 30), 56789, '+491772635467')
(6, 'Niamh', 'Murphy', 'ENG', 'IRI', datetime.date(1995, 9, 8), 67890, '+491231231232')


Exatamente o que estávamos esperando. A função também funciona com queries mais complexas, como essa abaixo, envolvendo JOIN entre as tabelas de course e client (curso e cliente, em inglês, respectivamente) e mais algumas queries para testarmos. 

In [20]:
q2 = """
SELECT last_name, dob
FROM teacher;
"""

connection = create_db_connection("172.17.0.2", "root", pw, db)
results = read_query(connection, q2)

for result in results:
  print(result)

MySQL Database connection successful
('Smith', datetime.date(1985, 4, 20))
('Martin', datetime.date(1970, 2, 17))
('Wang', datetime.date(1990, 11, 12))
('Müller-Rossi', datetime.date(1987, 7, 7))
('Ivanova', datetime.date(1963, 5, 30))
('Murphy', datetime.date(1995, 9, 8))


In [21]:
q3 = """
SELECT *
FROM course
WHERE language = 'ENG'
ORDER BY start_date DESC;
"""

connection = create_db_connection("172.17.0.2", "root", pw, db)
results = read_query(connection, q3)

for result in results:
  print(result)

MySQL Database connection successful
(19, 'Intermediate English', 'ENG', 'B2', 10, datetime.date(2020, 3, 29), 0, 1, 104)
(12, 'English for Logistics', 'ENG', 'A1', 10, datetime.date(2020, 2, 1), 1, 1, 105)
(13, 'Beginner English', 'ENG', 'A2', 40, datetime.date(2019, 11, 12), 0, 6, 101)
(14, 'Intermediate English', 'ENG', 'B2', 40, datetime.date(2019, 11, 12), 0, 6, 101)
(15, 'Advanced English', 'ENG', 'C1', 40, datetime.date(2019, 11, 12), 0, 6, 101)


In [22]:
q4 = """
SELECT first_name, last_name, phone_no
FROM teacher
WHERE dob < '1990-01-01';
"""

connection = create_db_connection("172.17.0.2", "root", pw, db)
results = read_query(connection, q4)

for result in results:
  print(result)

MySQL Database connection successful
('James', 'Smith', '+491774553676')
('Stefanie', 'Martin', '+491234567890')
('Friederike', 'Müller-Rossi', '+492345678901')
('Isobel', 'Ivanova', '+491772635467')


In [23]:
q5 = """
SELECT course.course_id, course.course_name, course.language, client.client_name, client.address
FROM course
JOIN client
ON course.client = client.client_id
WHERE course.in_school = FALSE;
"""

connection = create_db_connection("172.17.0.2", "root", pw, db)
results = read_query(connection, q5)

for result in results:
  print(result)

MySQL Database connection successful
(13, 'Beginner English', 'ENG', 'Big Business Federation', '123 Falschungstraße, 10999 Berlin')
(14, 'Intermediate English', 'ENG', 'Big Business Federation', '123 Falschungstraße, 10999 Berlin')
(15, 'Advanced English', 'ENG', 'Big Business Federation', '123 Falschungstraße, 10999 Berlin')
(17, 'Français intermédiaire', 'FRA', 'Big Business Federation', '123 Falschungstraße, 10999 Berlin')
(19, 'Intermediate English', 'ENG', 'Banko Bank', '12 Betrugstraße, 12345 Berlin')
(20, 'Fortgeschrittenes Russisch', 'RUS', 'AutoMaker AG', '20 Künstlichstraße, 10023 Berlin')


Muito bom.

Para nossos pipelines de dados e fluxos de trabalho em Python, podemos querer obter esses resultados em formatos diferentes para torná-los mais úteis ou prontos para manipulação.

Vamos ver alguns exemplos para entender como podemos fazer isso.

### Formatando resultados em formato de lista

Agora podemos atribuir os resultados a uma lista, para usar mais em nossos aplicativos ou scripts python.

O código a seguir retorna os resultados de nossa consulta como uma lista de tuplas.

In [25]:
#Initialise empty list
from_db = []

# Loop over the results and append them into our list, different styles

# Returns a list of tuples
for result in results:
  result = result
  from_db.append(result)
    
print(from_db)

[(13, 'Beginner English', 'ENG', 'Big Business Federation', '123 Falschungstraße, 10999 Berlin'), (14, 'Intermediate English', 'ENG', 'Big Business Federation', '123 Falschungstraße, 10999 Berlin'), (15, 'Advanced English', 'ENG', 'Big Business Federation', '123 Falschungstraße, 10999 Berlin'), (17, 'Français intermédiaire', 'FRA', 'Big Business Federation', '123 Falschungstraße, 10999 Berlin'), (19, 'Intermediate English', 'ENG', 'Banko Bank', '12 Betrugstraße, 12345 Berlin'), (20, 'Fortgeschrittenes Russisch', 'RUS', 'AutoMaker AG', '20 Künstlichstraße, 10023 Berlin')]


### Formatando o resultado em uma lista de listas

In [26]:
# Retorna uma lista de listas
from_db = []

for result in results:
  result = list(result)
  from_db.append(result)

print(from_db)

[[13, 'Beginner English', 'ENG', 'Big Business Federation', '123 Falschungstraße, 10999 Berlin'], [14, 'Intermediate English', 'ENG', 'Big Business Federation', '123 Falschungstraße, 10999 Berlin'], [15, 'Advanced English', 'ENG', 'Big Business Federation', '123 Falschungstraße, 10999 Berlin'], [17, 'Français intermédiaire', 'FRA', 'Big Business Federation', '123 Falschungstraße, 10999 Berlin'], [19, 'Intermediate English', 'ENG', 'Banko Bank', '12 Betrugstraße, 12345 Berlin'], [20, 'Fortgeschrittenes Russisch', 'RUS', 'AutoMaker AG', '20 Künstlichstraße, 10023 Berlin']]


### Formatando o resultado em um [DataFrame do Pandas](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html)

Para os analistas de dados usando Python, o [pandas](https://pandas.pydata.org/pandas-docs/stable/index.html) (texto em inglês) é o nosso velho amigo, belo e confiável. É muito simples converter a saída do nosso banco de dados em um DataFrame. A partir daí, as possibilidades são infinitas!

In [27]:
# Retorna uma lista de listas e cria um DataFrame do Pandas
from_db = []

for result in results:
  result = list(result)
  from_db.append(result)


columns = ["course_id", "course_name", "language", "client_name", "address"]
df = pd.DataFrame(from_db, columns=columns)

display(df)

course_id                 course_name language              client_name  \
0         13            Beginner English      ENG  Big Business Federation   
1         14        Intermediate English      ENG  Big Business Federation   
2         15            Advanced English      ENG  Big Business Federation   
3         17      Français intermédiaire      FRA  Big Business Federation   
4         19        Intermediate English      ENG               Banko Bank   
5         20  Fortgeschrittenes Russisch      RUS             AutoMaker AG   

                             address  
0  123 Falschungstraße, 10999 Berlin  
1  123 Falschungstraße, 10999 Berlin  
2  123 Falschungstraße, 10999 Berlin  
3  123 Falschungstraße, 10999 Berlin  
4      12 Betrugstraße, 12345 Berlin  
5   20 Künstlichstraße, 10023 Berlin

Espero que possa ver as possibilidades se desdobrando diante de você. Com apenas algumas linhas de código, podemos extrair facilmente todos os dados que podemos manipular dos bancos de dados relacionais em que eles residem e trazê-los para nossos pipelines de análise de dados de última geração. Isso é algo realmente útil.

## Atualizando registros

Quando mantemos um banco de dados, às vezes precisaremos fazer alterações nos registros existentes. Nesta seção, veremos como fazer isso.

Digamos que a nossa empresa fictícia seja notificada de que um de seus clientes existentes, a Big Business Federation, está mudando de escritório para 23 Fingiertweg, 14534 Berlin. Nesse caso, o administrador do banco de dados (nós!) precisará fazer algumas alterações.

Felizmente, podemos fazer isso com nossa função execute\_query junto com a instrução [UPDATE](https://dev.mysql.com/doc/refman/8.0/en/update.html) (texto em inglês) do SQL.

### Atualizando o endereço de um cliente

In [28]:
update = """
UPDATE client 
SET address = '23 Fingiertweg, 14534 Berlin' 
WHERE client_id = 101;
"""

connection = create_db_connection("172.17.0.2", "root", pw, db)
execute_query(connection, update)

MySQL Database connection successful
Query successful


Note que a cláusula WHERE é muito importante. Se executarmos esse comando sem a cláusula WHERE, todos os endereços de todos os registros em nossa tabela Client serão atualizados para 23 Fingiertweg. Não é exatamente isso que queremos fazer.

Observe também que usamos "WHERE client_id = 101" na consulta UPDATE. Também seria possível usar "WHERE client_name = 'Big Business Federation'" ou "WHERE address = '123 Falschungstraße, 10999 Berlin'" ou mesmo "WHERE address LIKE '%Falschung%'".

O importante é que a cláusula WHERE nos permite identificar exclusivamente o registro (ou registros) que queremos atualizar.

Agora, precisamos conferir a atualização:

In [30]:
q1 = """
SELECT *
FROM client
WHERE client_id = 101;
"""

connection = create_db_connection("172.17.0.2", "root", pw, db)
results = read_query(connection, q1)

for result in results:
  print(result)

MySQL Database connection successful
(101, 'Big Business Federation', '23 Fingiertweg, 14534 Berlin', 'NGO')


## Deletando registros
### Deletando um curso

Também é possível usar nossa função execute\_query para excluir registros, usando [DELETE](https://dev.mysql.com/doc/refman/8.0/en/delete.html) (texto em inglês).

Ao usar SQL com bancos de dados relacionais, precisamos ter cuidado ao usar o operador DELETE. Este não é o Windows. Não há um alerta dizendo "Tem certeza de que deseja excluir isso?" em uma janela de pop-up e não há uma lixeira para a reciclagem. Uma vez que excluímos algo, esse algo realmente se foi.

Dito isso, nós às vezes realmente precisamos apagar coisas. Então, vamos ver isso na prática, apagando um curso da nossa tabela Course.

Antes de mais nada, vamos nos lembrar dos cursos que temos.

![image-174](https://www.freecodecamp.org/portuguese/news/content/images/2022/02/image-174.png)

Digamos que o curso 20, 'Fortgeschrittenes Russisch' (que é 'Russo avançado' para você e para mim), está chegando ao fim. Então, precisamos removê-lo do nosso banco de dados.

A essa altura, você não ficará surpreso com a forma como fazemos isso - salve o comando SQL como uma string e, em seguida, passe-o para a nossa função execute\_query.

In [31]:
q1 = """
SELECT *
FROM course;
"""

connection = create_db_connection("172.17.0.2", "root", pw, db)
results = read_query(connection, q1)

from_db = []

for result in results:
  print(result)

MySQL Database connection successful
(12, 'English for Logistics', 'ENG', 'A1', 10, datetime.date(2020, 2, 1), 1, 1, 105)
(13, 'Beginner English', 'ENG', 'A2', 40, datetime.date(2019, 11, 12), 0, 6, 101)
(14, 'Intermediate English', 'ENG', 'B2', 40, datetime.date(2019, 11, 12), 0, 6, 101)
(15, 'Advanced English', 'ENG', 'C1', 40, datetime.date(2019, 11, 12), 0, 6, 101)
(16, 'Mandarin für Autoindustrie', 'MAN', 'B1', 15, datetime.date(2020, 1, 15), 1, 3, 103)
(17, 'Français intermédiaire', 'FRA', 'B1', 18, datetime.date(2020, 4, 3), 0, 2, 101)
(18, 'Deutsch für Anfänger', 'DEU', 'A2', 8, datetime.date(2020, 2, 14), 1, 4, 102)
(19, 'Intermediate English', 'ENG', 'B2', 10, datetime.date(2020, 3, 29), 0, 1, 104)
(20, 'Fortgeschrittenes Russisch', 'RUS', 'C1', 4, datetime.date(2020, 4, 8), 0, 5, 103)


Vamos deletar o curso com ID 20: course_id 20 - 'Fortgeschrittenes Russisch', usando a cláusula DELETE:

In [32]:
delete_course = """
DELETE FROM course WHERE course_id = 20;
"""

connection = create_db_connection("172.17.0.2", "root", pw, db)
execute_query(connection, delete_course)

MySQL Database connection successful
Query successful


Agora, vamos checar se o curso foi deletado: 

In [33]:
q1 = """
SELECT *
FROM course;
"""

connection = create_db_connection("172.17.0.2", "root", pw, db)
results = read_query(connection, q1)

from_db = []

for result in results:
  print(result)

MySQL Database connection successful
(12, 'English for Logistics', 'ENG', 'A1', 10, datetime.date(2020, 2, 1), 1, 1, 105)
(13, 'Beginner English', 'ENG', 'A2', 40, datetime.date(2019, 11, 12), 0, 6, 101)
(14, 'Intermediate English', 'ENG', 'B2', 40, datetime.date(2019, 11, 12), 0, 6, 101)
(15, 'Advanced English', 'ENG', 'C1', 40, datetime.date(2019, 11, 12), 0, 6, 101)
(16, 'Mandarin für Autoindustrie', 'MAN', 'B1', 15, datetime.date(2020, 1, 15), 1, 3, 103)
(17, 'Français intermédiaire', 'FRA', 'B1', 18, datetime.date(2020, 4, 3), 0, 2, 101)
(18, 'Deutsch für Anfänger', 'DEU', 'A2', 8, datetime.date(2020, 2, 14), 1, 4, 102)
(19, 'Intermediate English', 'ENG', 'B2', 10, datetime.date(2020, 3, 29), 0, 1, 104)


### Restaurando o curso

In [34]:
restore_russian = """
INSERT INTO course VALUES
(20, 'Fortgeschrittenes Russisch', 'RUS', 'C1',  4, '2020-04-08',  FALSE, 5, 103);
"""

connection = create_db_connection("172.17.0.2", "root", pw, db)
execute_query(connection, restore_russian)


q1 = """
SELECT *
FROM course;
"""

connection = create_db_connection("172.17.0.2", "root", pw, db)
results = read_query(connection, q1)

from_db = []

for result in results:
  print(result)

MySQL Database connection successful
Query successful
MySQL Database connection successful
(12, 'English for Logistics', 'ENG', 'A1', 10, datetime.date(2020, 2, 1), 1, 1, 105)
(13, 'Beginner English', 'ENG', 'A2', 40, datetime.date(2019, 11, 12), 0, 6, 101)
(14, 'Intermediate English', 'ENG', 'B2', 40, datetime.date(2019, 11, 12), 0, 6, 101)
(15, 'Advanced English', 'ENG', 'C1', 40, datetime.date(2019, 11, 12), 0, 6, 101)
(16, 'Mandarin für Autoindustrie', 'MAN', 'B1', 15, datetime.date(2020, 1, 15), 1, 3, 103)
(17, 'Français intermédiaire', 'FRA', 'B1', 18, datetime.date(2020, 4, 3), 0, 2, 101)
(18, 'Deutsch für Anfänger', 'DEU', 'A2', 8, datetime.date(2020, 2, 14), 1, 4, 102)
(19, 'Intermediate English', 'ENG', 'B2', 10, datetime.date(2020, 3, 29), 0, 1, 104)
(20, 'Fortgeschrittenes Russisch', 'RUS', 'C1', 4, datetime.date(2020, 4, 8), 0, 5, 103)


Esse comando também funciona para apagar colunas inteiras, usando [DROP COLUMN](https://www.w3schools.com/sql/sql_ref_drop_column.asp) e tabelas inteiras, usando [DROP TABLE](https://www.w3schools.com/sql/sql_ref_drop_table.asp) (ambos os textos de referência em inglês), mas não abordaremos esses comandos neste tutorial.

No entanto, vá em frente e experimente-os - não importa se você excluir uma coluna ou tabela de um banco de dados para uma escola fictícia. É uma boa ideia se familiarizar com esses comandos antes de passar para um ambiente de produção.

### E o [CRUD](https://pt.wikipedia.org/wiki/CRUD)?

A essa altura, já podemos concluir as quatro operações principais para o armazenamento de dados persistentes.

Aprendemos a:

-   Create (Criar) - bancos de dados, tabelas e registros inteiramente novos
-   Read (Ler) - extrair dados de um banco de dados e armazenar em diversos formatos
-   Update (Atualizar) - fazer alterações nos registros existentes no banco de dados
-   Delete (Apagar) - remover registros que não são mais necessários

Poder fazer essas coisas é incrivelmente útil.

Antes de concluirmos, temos mais uma habilidade muito importante para aprender.

# Criando registros a partir de listas

Vimos, ao preencher nossas tabelas, que podemos utilizar o comando SQL INSERT em nossa função execute\_query para inserir registros em nosso banco de dados.

Dado que estamos usando Python para manipular nosso banco de dados SQL, seria útil poder obter uma estrutura de dados do Python, tal como uma [lista](https://www.w3schools.com/python/python_lists.asp) (texto em inglês), e inseri-la diretamente em nosso banco de dados.

Isso pode ser útil quando queremos armazenar logs de atividade do usuário em um aplicativo de mídia social que escrevemos em Python ou entradas de usuários em uma página Wiki que criamos, por exemplo. Existem tantos usos possíveis para isso quantos você possa imaginar.

Esse método também é mais seguro se nosso banco de dados estiver aberto para nossos usuários a qualquer momento, pois ajuda a prevenir ataques de [injeção de SQL](https://pt.wikipedia.org/wiki/Inje%C3%A7%C3%A3o_de_SQL), que podem [danificar ou até destruir](https://www.lucidchart.com/pages/er-diagrams) (texto em inglês) todo o nosso banco de dados.

Para fazer isso, escreveremos uma função usando o método [executemany()](https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlcursor-executemany.html), em vez do método [execute()](https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlcursor-execute.html) (textos de referência em inglês), para aceitar mais um argumento.

In [35]:
def execute_list_query(connection, sql, val):
    cursor = connection.cursor()
    try:
        cursor.executemany(sql, val)
        connection.commit()
        print("Query successful")
    except Error as err:
        print(f"Error: '{err}'")

Agora que temos a função, precisamos definir um comando SQL ('sql') e uma lista contendo os valores que desejamos inserir no banco de dados ('val'). Os valores devem ser armazenados em uma [lista](https://www.w3schools.com/python/python_lists.asp) de [tuplas](https://www.w3schools.com/python/python_tuples.asp) (textos de referência em inglês), que é uma maneira bastante comum de armazenar dados em Python.

Para adicionar dois novos professores ao banco de dados, podemos escrever um código como este:

### Adicionando Professores

In [36]:
sql = '''
    INSERT INTO teacher (teacher_id, first_name, last_name, language_1, language_2, dob, tax_id, phone_no) 
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
    '''
val = [
    (7, 'Hank', 'Dodson', 'ENG', None, '1991-12-23', 11111, '+491772345678'), 
    (8, 'Sue', 'Perkins', 'MAN', 'ENG', '1976-02-02', 22222, '+491443456432')
]


connection = create_db_connection("172.17.0.2", "root", pw, db)
execute_list_query(connection, sql, val)

MySQL Database connection successful
Query successful


Observe aqui que no código 'sql' usamos o '%s' como um espaço reservado para nosso valor. A semelhança com o ['%s'](https://stackoverflow.com/questions/4288973/whats-the-difference-between-s-and-d-in-python-string-formatting/48660475) para uma string em Python é apenas coincidência (e francamente, muito confusa), pois devemos usar '%s' para todos os tipos de dados (strings, inteiros, datas etc) com o MySQL Python Conector.

Você pode ver vários casos no [Stackoverflow](https://stackoverflow.com/questions/20818155/not-all-parameters-were-used-in-the-sql-statement-python-mysql/20818201) em que alguém ficou confuso e tentou usar ['%d'](https://stackoverflow.com/questions/4288973/whats-the-difference-between-s-and-d-in-python-string-formatting/48660475) para inteiros porque estava acostumado a fazer isso em Python. Isso não funcionará aqui - precisamos usar um '%s' para cada coluna para qual queremos adicionar um valor.

A função executemany, então, pega cada tupla em nossa lista 'val' e insere o valor relevante para aquela coluna no lugar do espaço reservado e executa o comando SQL para cada tupla contida na lista.

Isso pode ser feito para várias linhas de dados, desde que sejam formatadas corretamente. Em nosso exemplo, adicionaremos apenas dois novos professores, para fins ilustrativos, mas em princípio podemos adicionar quantos quisermos.

Vamos executar este comando e adicionar os professores ao nosso banco de dados.

In [37]:
q1 = """
SELECT *
FROM teacher;
"""

connection = create_db_connection("172.17.0.2", "root", pw, db)
results = read_query(connection, q1)

from_db = []

for result in results:
  print(result)

MySQL Database connection successful
(1, 'James', 'Smith', 'ENG', None, datetime.date(1985, 4, 20), 12345, '+491774553676')
(2, 'Stefanie', 'Martin', 'FRA', None, datetime.date(1970, 2, 17), 23456, '+491234567890')
(3, 'Steve', 'Wang', 'MAN', 'ENG', datetime.date(1990, 11, 12), 34567, '+447840921333')
(4, 'Friederike', 'Müller-Rossi', 'DEU', 'ITA', datetime.date(1987, 7, 7), 45678, '+492345678901')
(5, 'Isobel', 'Ivanova', 'RUS', 'ENG', datetime.date(1963, 5, 30), 56789, '+491772635467')
(6, 'Niamh', 'Murphy', 'ENG', 'IRI', datetime.date(1995, 9, 8), 67890, '+491231231232')
(7, 'Hank', 'Dodson', 'ENG', None, datetime.date(1991, 12, 23), 11111, '+491772345678')
(8, 'Sue', 'Perkins', 'MAN', 'ENG', datetime.date(1976, 2, 2), 22222, '+491443456432')


Esta é mais uma função muito útil, permitindo-nos pegar dados gerados em nossos scripts e aplicativos Python e inseri-los diretamente em nosso banco de dados.